import "./globals.css";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Background from "@/components/Background";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Globactis",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className="h-full">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen relative`}
      >
        {/* Background behind everything (no children passed) */}
        <div className="fixed inset-0 z-0 pointer-events-none">
          <Background
            beamWidth={2}
            beamHeight={150}
            beamNumber={10}
            lightColor="#FEB50F"
            speed={2}
            noiseIntensity={1.5}
            scale={0.2}
            rotation={40}
          />
        </div>

        {/* App content above background */}
        <div className="relative z-10">{children}</div>
      </body>
    </html>
  );
}
